name: "release"
description: "release"

inputs:
  arch_name:
    description: "architecture name"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Add binary to release
      if: ${{ github.event_name == 'release' }}
      uses: shogo82148/actions-upload-release-asset@v1.6.6
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: src/mcfost
        asset_name: ${{ format('mcfost_{0}', inputs.arch_name) }}
