name: build-gfortran-linux

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MCFOST_INSTALL: "/home/runner/work"
      MCFOST_NO_XGBOOST: "yes"
      SYSTEM: "gfortran"
      MCFOST_GIT: "1"

    steps:
    - uses: actions/checkout@v2

    # Cache dependencies for mcfost to avoid downloading/installing them each time this workflow runs
    - name: cache dependencies
      id: cache-deps
      uses: john-shaffer/cache@main     # Need this version to unpack the cache tar with sudo
      env:
        cache-name: cache-mcfost-dependencies
      with:
        path: |
          /home/runner/work/include
          /home/runner/work/lib
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: update gcc to v12 # Using gcc-11 will return a bug when compiling gas/wavelengths_gas.f90
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-12 12
        sudo update-alternatives --config gcc

    # Only do this (lengthy) setup if dependency cache not found
    - if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
      name: prepare mcfost environment
      run: |
        cd lib
        ./install.sh
        cd ..

    - name: compile mcfost
      run: |
        cd src
        make all

    - name: add binary to release
      if: ${{ github.event_name == 'release' }}
      uses: shogo82148/actions-upload-release-asset@v1.6.6
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/mcfost
          asset_name: mcfost_linux-x86_64

    - name: add library to release
      if: ${{ github.event_name == 'release' }}
      uses: shogo82148/actions-upload-release-asset@v1.6.6
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src/libmcfost.a
          asset_name: libmcfost_linux-x86_64.a
