# This is a basic workflow to help you get started with Actions

name: build-gfortran-linux

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MCFOST_INSTALL: "$HOME"
      MCFOST_NO_XGBOOST: "yes"
      SYSTEM: "gfortran"
      MCFOST_GIT: "1"

    steps:
    - uses: actions/checkout@v2

    - name: remove "#" from all deb-scr lines
      run: sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list

    - name: update apt-get
      run: sudo apt-get update

    - name: install build-essential
      run: sudo apt-get install build-essential
      
    - name: install gfortran
      run: sudo apt-get install gfortran

    - name: prepare HDF5 environment
      run: sudo apt-get build-dep hdf5

    - name: install HDF5
      run: sudo apt-get install libhdf5-serial-dev

    - name: install cfitsio
      run: sudo apt install libcfitsio-dev

    - name: install voro++
      run: sudo apt install voro++

    - name: install sprng2
      run: sudo apt-get install libsprng2

    # - name: check path
    #   run: pwd

    # - name: prepare mcfost env
    #   run: |
    #        cd lib
    #        ./install.sh
    #        cd ..

    - name: compile mcfost
      run: |
           cd src
           make all INCLUDE=-I/usr/local/include LIBS=/usr/local/lib

      

      
