# This is a basic workflow to help you get started with Actions

name: build-gfortran-macos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      run: git log --pretty=format:"%H %d"

    - name: install gfortran
      run: brew reinstall gcc

    - name: install hdf5
      run: brew install hdf5

    - name: install cfitsio
      run: brew install cfitsio

    - name: get custom taps needed for mcfost
      run: brew tap danieljprice/all

    - name: install voro++
      run: brew install voro-dev

    - name: install sprng2
      run: brew install sprng2

    - name: compile mcfost
      env:
           MCFOST_INSTALL: "/usr/local"
           MCFOST_NO_XGBOOST: "yes"
           SYSTEM: "gfortran"
      run: |
           cd src
           make all INCLUDE=-I/usr/local/include LIBS=/usr/local/lib MCFOST_GIT=1
