name: release

on:
  release:
    types:
      - published

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build/macos
      - uses: ./.github/actions/release
        with:
          arch_name: macos

  linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build/linux
      - uses: ./.github/actions/release
        with:
          arch_name: linux-x86_64
