name: test-suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MCFOST_NO_XGBOOST: yes
  SYSTEM: gfortran
  MCFOST_GIT: "1"

jobs:
  macos:
    runs-on: macos-12
    env:
      HDF5_DIR: /usr/local
      MCFOST_INSTALL: /usr/local
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        uses: ./.github/actions/dependencies/macos

      - name: compile mcfost
        working-directory: src
        run: make all

      - name: test
        uses: ./.github/actions/test

  linux:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64
    env:
      MCFOST_INSTALL: /opt/local
    steps:
      - uses: actions/checkout@v2

      - run: dnf install -y redhat-lsb-core wget

      - run: git config --global --add safe.directory $PWD

      - name: build and install dependencies
        uses: ./.github/actions/dependencies/linux

      - name: compile mcfost
        working-directory: src
        run: make all

      - name: test
        uses: ./.github/actions/test
