name: test-suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MCFOST_NO_XGBOOST: yes
  SYSTEM: gfortran
  MCFOST_GIT: "1"
  MCFOST_INSTALL: /tmp/mcfost-deps

jobs:
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: ensure GNU gcc is used, not clang
        run: |
          brew reinstall gcc@13
          cd /usr/local/bin
          ln -vfs gcc-13 gcc
          ln -vfs g++-13 g++
          ln -vfs gfortran-13 gfortran

      - name: build and install dependencies
        uses: ./.github/actions/dependencies/linux

      - name: compile mcfost
        working-directory: src
        run: make all

      - name: test
        uses: ./.github/actions/test

  linux:
    runs-on: ubuntu-22.04
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
      - uses: actions/checkout@v2

      - name: install deps missing in container
        run: |
          dnf install -y redhat-lsb-core wget
          git config --global --add safe.directory $PWD

      - name: build and install dependencies
        uses: ./.github/actions/dependencies/linux

      - name: compile mcfost
        working-directory: src
        run: make all

      - name: test
        uses: ./.github/actions/test
